version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: e44f84gs
      MYSQL_DATABASE: dindo-pet
      JDBC_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    ports:
      - "8080:8080"